env:
  CODECOV_TOKEN: c078b8d5-ad2b-4c0d-a5c7-ac8266f699bc
  JULIA_NUM_THREADS: auto
  
steps:
  - label: "CI Buildkite"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e '
        using Pkg
        Pkg.add("QuantumSavory")
        Pkg.build("QuantumSavory")
        Pkg.test("QuantumSavory")'
